version: '3.8'

services:
  backend:
    build: ./backend
    container_name: learnscribe-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    container_name: learnscribe-frontend
    ports:
      - "3000:80"